#!/bin/bash
clear

## 10-100
SPEED=20

if [[ $# -eq 1 ]] && [[ $1 == "reset" ]]; then
    kubectl scale deploy/inflate-arm64 deploy/inflate-on-demand deploy/gpu-nvidia deploy/inflate --replicas=0
    exit 0
fi

function cmd() {
    local cmd="${1}"
    if [[ ! -z ${cmd} ]]; then
        echo -en "${cmd}" | pv -qL "${SPEED}"
        read -n 1 -s
        echo -e "\n"
        eval $cmd
        echo -en "\n🐶> "
        read -n 1 -s
    else
        echo -en "\n🐶> "
        read -n 1 -s
    fi
}

cat karpenter-banner.ascii
echo -e "\n ================================================================================== \n"

cmd ""
cmd "kubectl get provisioner default -o yaml | less"
cmd "kubectl get awsnodetemplate default -o yaml | less"
cmd "kubectl scale deployment inflate --replicas=100"
cmd "kubectl get deployment inflate -o yaml | less"
cmd "kubectl scale deployment inflate --replicas=0"
cmd "kubectl scale deployment/inflate-arm64 --replicas=100"
cmd "kubectl get deployment inflate-arm64 -o yaml | less"
cmd "kubectl scale deployment/inflate-on-demand --replicas=100"
cmd "kubectl scale deployment/gpu-nvidia --replicas=2"
cmd "watch kgna"
cmd "kubectl scale deployment/inflate-arm64 --replicas=0"
cmd "kubectl scale deployment/inflate-on-demand --replicas=0"
cmd "kubectl scale deployment/gpu-nvidia --replicas=0"
