#!/bin/bash
clear

## 10-100
SPEED=20

cat karpenter-banner.ascii
echo -e "\n ================================================================================== \n"

echo -en "🐶> "
read -n 1 -s

echo -en "kubectl get provisioner default | less" | pv -qL "${SPEED}"
read -n 1 -s
less provisioners/default.yaml
echo -en "\n🐶> "
read -n 1 -s

echo -en "kubectl scale deployment/inflate --replicas=10" | pv -qL "${SPEED}"
read -n 1 -s
echo -e "\n"
kubectl scale deployment/inflate --replicas=10
echo -en "\n🐶> "
read -n 1 -s
echo -en "kubectl get deployment inflate -o yaml | less" | pv -qL "${SPEED}"
read -n 1 -s
less workloads/inflate.yaml

echo -en "\n🐶> "
read -n 1 -s
echo -en "kubectl logs deployment/karpenter -n karpenter -c controller | tail" | pv -qL "${SPEED}"
read -n 1 -s
kubectl logs deployment/karpenter -n karpenter -c controller | tail | less

echo -en "\n🐶> "
read -n 1 -s
echo -en "kubectl scale deployment/inflate-arm64 --replicas=10" | pv -qL "${SPEED}"
read -n 1 -s
echo -e "\n"
kubectl scale deployment/inflate-arm64 --replicas=10
echo -en "\n🐶> "
read -n 1 -s
echo -en "kubectl get deployment inflate-arm64 -o yaml | less" | pv -qL "${SPEED}"
read -n 1 -s
less workloads/inflate-arm64.yaml

echo -en "\n🐶> "
read -n 1 -s
echo -en "kubectl scale deployment/inflate-on-demand --replicas=10" | pv -qL "${SPEED}"
read -n 1 -s
echo -e "\n"
kubectl scale deployment/inflate-on-demand --replicas=10
echo -en "\n🐶> "
read -n 1 -s
echo -en "kubectl get deployment inflate-on-demand -o yaml | less" | pv -qL "${SPEED}"
read -n 1 -s
less workloads/inflate-on-demand.yaml

# echo -en "\n🐶> "
# read -n 1 -s
# echo -en "kubectl scale deployment/spot-fast-ahem --replicas=10" | pv -qL "${SPEED}"
# read -n 1 -s
# echo -e "\n"
# kubectl scale deployment/spot-fast-ahem --replicas=10
# echo -en "\n🐶> "
# read -n 1 -s
# echo -en "kubectl get deployment spot-fast-ahem -o yaml | less" | pv -qL "${SPEED}"
# read -n 1 -s
# less workloads/spot-fast-ahem.yaml

# echo -en "\n🐶> "
# read -n 1 -s
# echo -en "kubectl scale deployment/spot-slow-ahem --replicas=10" | pv -qL "${SPEED}"
# read -n 1 -s
# echo -e "\n"
# kubectl scale deployment/spot-slow-ahem --replicas=10
# echo -en "\n🐶> "
# read -n 1 -s
# echo -en "kubectl get deployment spot-slow-ahem -o yaml | less" | pv -qL "${SPEED}"
# read -n 1 -s
# less workloads/spot-slow-ahem.yaml

echo -en "\n🐶> "
read -n 1 -s
echo -en "kubectl scale deployment/spot-od-split-ahem --replicas=10"  | pv -qL "${SPEED}"
read -n 1 -s
echo -e "\n"
kubectl scale deployment/spot-od-split-ahem --replicas=10
echo -en "\n🐶> "
read -n 1 -s
echo -en "kubectl get deployment spot-od-split-ahem -o yaml | less" | pv -qL "${SPEED}"
read -n 1 -s
less workloads/spot-od-split-ahem.yaml

echo -en "\n🐶> "
read -n 1 -s
echo -en "kubectl scale deployment/gpu-nvidia --replicas=2" | pv -qL "${SPEED}"
read -n 1 -s
echo -e "\n"
kubectl scale deployment/gpu-nvidia --replicas=2
echo -en "\n🐶> "
read -n 1 -s
echo -en "kubectl get deployment gpu-nvidia -o yaml | less" | pv -qL "${SPEED}"
read -n 1 -s
less workloads/gpu-nvidia.yaml

echo -en "\n🐶> "
read -n 1 -s

./deflate
