apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  limits:
    resources:
      cpu: 1k
  provider:
    securityGroupSelector:
      karpenter.sh/discovery: karpenter-kubecon-eu-central-1
    subnetSelector:
      karpenter.sh/discovery: karpenter-kubecon-eu-central-1
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
    - spot
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
    - arm64
  ttlSecondsAfterEmpty: 10
